image: maven:3.9.8

#
# Define the environment-specific variables
#

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

#
# Define the stages of our pipeline
#

stages:
  - build 
  - test
  - deploy-staging

build:
  stage: build
  script:
    - mvn  -U -V -e -B clean -DskipTests package 
  only:
    - merge_requests

test:
  stage: test
  script:
    - mvn -U -V -e -B clean test 
  only:
    - merge_requests
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml  

deploy-staging:
  stage: deploy-staging
  script:
    - mvn -U -V -e -B clean -DskipTests deploy -DmuleDeploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'